spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/reservation
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org:
      springframework: INFO

server:
  port: 8080
